@startuml
'https://plantuml.com/activity-diagram-beta

start
:Select Add a Password Option;
:Enter Password Name;
:Enter Password Code;

if (Add additional information?) then (Yes)
  fork
  if (Add email?) then (Yes)
    :Enter Email;
  endif
  fork again
  if (Add phone number?) then (Yes)
    :Enter Phone Number;
  endif
  end fork
endif

:Create Password Entry;
if (Save to Password Library?) then (Yes);
:Show Success Message;
else(No)
endif

stop

@enduml