@startuml
'https://plantuml.com/sequence-diagram

actor User
participant PasswordLibrary
participant PasswordEntry

User -> PasswordLibrary: Enter Password Name
User -> PasswordLibrary: Enter Password Code
alt Add Additional Information?
    User -> PasswordLibrary: Enter Email
    PasswordLibrary -> PasswordEntry: Decorate with Email
    User -> PasswordLibrary: Enter Phone Number
    PasswordLibrary -> PasswordEntry: Decorate with Phone Number
end
PasswordLibrary -> PasswordEntry: Create Password Entry
PasswordLibrary -> PasswordLibrary: Save Password Entry
PasswordLibrary -> User: Show Success Message

@enduml