@startuml
'https://plantuml.com/activity-diagram-beta

start
:Select Delete Option;
:Enter the Index of Password Entry to Delete;
if (Valid Index?) then (Yes)
  :Remove Password from Password Library;
  :Show Success Message;
else (No)
  :Display Message Invalid Index;
endif
stop

@enduml
