  @startuml
'https://plantuml.com/class-diagram

' ---- Singleton ----
class PasswordLibrary {
  -passwords: List<PasswordEntry>
  -instance: PasswordLibrary
  -memento: Memento
  +getInstance(): PasswordLibrary
  +addPassword(password: PasswordEntry): void
  +removePassword(index: int): void
  +getPasswordList(): List<PasswordEntry>
  +printPasswordList(): void
  +printPasswordEntry(index: int): void
  +searchPasswordByName(name: String): void
  +sortByName(): void
  +sortByDateAdded(): void
  +saveState(): void
  +restoreState(): void
}

PasswordLibrary o-- PasswordEntry
PasswordLibrary *-- Memento

' ---- Memento ----
class Memento {
  -state: List<PasswordEntry>
  +getState(): List<PasswordEntry>
  +setState(state: List<PasswordEntry>): void
}

' ---- Decorator ----
interface PasswordEntry {
  +getInfo(): String
  +getName(): String
  +getCreateTime(): String
}

class BasicPasswordEntry {
  -name: String
  -password: String
  -createTime: String
  +getInfo(): String
  +getName(): String
  +getCreateTime(): String
}

class EmailDecorator {
  -passwordEntry: PasswordEntry
  -email: String
  +getInfo(): String
  +getName(): String
  +getCreateTime(): String
}

class PhoneNumberDecorator {
  -passwordEntry: PasswordEntry
  -notes: String
  +getInfo(): String
  +getName(): String
  +getCreateTime(): String
}

PasswordEntry <|.. BasicPasswordEntry
PasswordEntry <|.. EmailDecorator
PasswordEntry <|.. PhoneNumberDecorator

' ---- State ----
class PasswordLibraryUIDisplay {
  -state: State
  +setState(state: State): void
  +getState(): State
  +switchMode(): void
}

interface State {
  +darkMode(context: PasswordLibraryUIDisplay): void
  +lightMode(context: PasswordLibraryUIDisplay): void
}

class DarkModeState {
  +darkMode(context: PasswordLibraryUIDisplay): void
  +lightMode(context: PasswordLibraryUIDisplay): void
}

class LightModeState {
  +darkMode(context: PasswordLibraryUIDisplay): void
  +lightMode(context: PasswordLibraryUIDisplay): void
}

State <|.. DarkModeState
State <|.. LightModeState
State --* PasswordLibraryUIDisplay

@enduml

