@startuml
'https://plantuml.com/activity-diagram-beta

start

:Select Restore Option;
if (Is There a Previous State?) then (Yes)
  :Load Last Saved State;
  :Restore Password to Previous State;
  :Show Success Message;
else (No)
  :Show Error Message;
endif

stop

@enduml
