@startuml
'https://plantuml.com/activity-diagram-beta

start
:Search for a Password by Name;
:Enter a Name;
if (Found?) then (Yes)
  :Display Search Results;
else (No)
  :Show Message Not Found;
endif
stop

@enduml
