@startuml
'https://plantuml.com/activity-diagram-beta

start
if (Choose a Sorting Option?) then (By Name)
  :Sorted in Alphabetical Order;
else (By Date Added)
  :Sorted in Chronological Order;
endif
:Display Sorted Password List;
stop

@enduml
