@startuml
'https://plantuml.com/activity-diagram-beta

start
:Select Switch Mode Option;
if (state?) then (LightModeState)
  :Switch to Light Mode;
else (DarkModeState)
  :Switch to Dark Mode;
endif
stop

@enduml
