@startuml
'https://plantuml.com/sequence-diagram
actor User
participant PasswordLibrary
participant PasswordEntry

User -> PasswordLibrary: Select Password to View
PasswordLibrary -> PasswordLibrary: Print List of Saved Password Names
PasswordLibrary -> PasswordLibrary: Validate Index
alt Index is Valid
    PasswordLibrary -> PasswordEntry: Retrieve Password Entry
    PasswordEntry -> PasswordEntry: Call getInfo()
    PasswordEntry -> PasswordEntry: Call getName()
    alt EmailDecorator outside BasicPasswordEntry
        PasswordEntry -> EmailDecorator: Call getInfo() from EmailDecorator
        EmailDecorator -> PasswordEntry: Add Email info to getInfo()
    end
    alt PhoneNumberDecorator outside BasicPasswordEntry
        PasswordEntry -> PhoneNumberDecorator: Call getInfo() from PhoneNumberDecorator
        PhoneNumberDecorator -> PasswordEntry: Add Phone Number info to getInfo()
    end
    alt EmailDecorator outside PhoneNumberDecorator
        PasswordEntry -> EmailDecorator: Call getInfo() from EmailDecorator
        EmailDecorator -> PasswordEntry: Call getInfo() from PhoneNumberDecorator
        PhoneNumberDecorator -> PasswordEntry: Add Phone Number info to getInfo()
        EmailDecorator -> PasswordEntry: Add Email info to getInfo()
    end
    alt PhoneNumberDecorator outside EmailDecorator
        PasswordEntry -> PhoneNumberDecorator: Call getInfo() from PhoneNumberDecorator
        PhoneNumberDecorator -> PasswordEntry: Call getInfo() from EmailDecorator
        EmailDecorator -> PasswordEntry: Add Email info to getInfo()
        PhoneNumberDecorator -> PasswordEntry: Add Phone Number info to getInfo()
    end
    PasswordLibrary -> PasswordEntry: Return Full Password Info
    User -> PasswordLibrary: View Password Info
else Invalid Index
    PasswordLibrary -> PasswordLibrary: Show Error Message "Invalid Index"
    User -> PasswordLibrary: See Error Message
end
@enduml