@startuml
'https://plantuml.com/activity-diagram-beta

start
:Open App;
:Print List of Saved Password Names;

:Enter Index of Password to View;
if (Valid Index?) then (Yes)
  :Display Password Entry Information;
else (No)
  :Show Message Invalid Index;
endif
stop

@enduml

